CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    email TEXT NOT NULL,
    ticket TEXT NOT NULL,
    ceilings TEXT NOT NULL,
    floors TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS alerts (
    alert_id INTEGER PRIMARY KEY,
    alert_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    ticket TEXT NOT NULL,
    price TEXT NOT NULL
);
